### ISSUE TITLE
Question regarding status.Ongoing label for already closed issues

### ISSUE THREAD

**Issue by HEARTOFAL1ON** [CS2103-AY1819S1-F11-1/main#174]
Should we remove them?

This is the [link](https://github.com/CS2103-AY1819S1-F11-1/main/issues?q=is%3Aissue+is%3Aclosed+label%3Astatus.Ongoing) that consolidates them

![image](https://user-images.githubusercontent.com/35895966/47951849-7de9c080-dfa1-11e8-973e-85aefb359f8a.png)

**Comment by YezhongZ** [comment]
Yes we should
