### ISSUE TITLE
Different behavior for edit repeat event in google and local implementation

### ISSUE THREAD

**Issue by YezhongZ** [CS2103-AY1819S1-F11-1/main#176]
**To Reproduce**
Steps to reproduce the behaviour:
1. `add n/Study with me s/tomorrow 9pm e/tomorrow 10pm rt/WEEKLY ru/2018-12-01`
2. `edit 4 s/8pm
`
Local behaviour:
change the index 4 event start Date to `today`, and time to `8pm`
![image](https://user-images.githubusercontent.com/39483787/47952154-fc486180-dfa5-11e8-9f82-696f0fcb9151.png)

Google behaviour
Google thinks the event on 2018-11-25 starts from `today 8pm `now. so it will generate all day event from today to `ru` date.
![image](https://user-images.githubusercontent.com/39483787/47952144-e89cfb00-dfa5-11e8-96b9-f8ae8662196c.png)

**Comment by YezhongZ** [comment]
Result of discussion:
they are describing the same thing, but the appearance is different.

**Comment by ChengYuuu** [comment]
Google thinks the event on 2018-11-25 starts from today 8pm now. so it will generate all day event from today to ru date.

* Should be generate all day event from today to *targeted event end date time*
