### ISSUE TITLE
Should we change the package named "seedu" to something else?

### ISSUE THREAD

**Issue by HEARTOFAL1ON** [CS2103-AY1819S1-F11-1/main#223]
I am referring to the `seedu` package. Should we change it to something more representative?

Actually, I feel that we should just keep `seedu`. Not just because it might be tedious to change so many things here and there which encompasses source codes and documentation.

Another rationale why we should KEEP is because we stated that our project was morphed from the `se-edu` ABL4 project thingy too.

@CS2103-AY1819S1-F11-1/developers, what do you all think?

**Comment by ChengYuuu** [comment]
Anything. Doesn't matter to me leh...

**Comment by HEARTOFAL1ON** [comment]
I think just keep `seedu` would be better. If not name it to what else??? We already renamed `seedu.address` to `seedu.scheduler`

**Comment by HEARTOFAL1ON** [comment]
I asked this because of this thread in the Slack forum

https://nus-cs2103-ay1819s1.slack.com/archives/CBQPHB7SN/p1540878520015000

![image](https://user-images.githubusercontent.com/35895966/47982634-6af2ff80-e10b-11e8-8f2a-e392b1741ecf.png)
![image](https://user-images.githubusercontent.com/35895966/47982647-78a88500-e10b-11e8-984f-eb43b86c481e.png)
![image](https://user-images.githubusercontent.com/35895966/47982662-83fbb080-e10b-11e8-8e08-522f60882ecf.png)
