### ISSUE TITLE
Check edit recurring events rt/ ru/ in google, esp index on intermediate event

### ISSUE THREAD

**Issue by Hexinyiyi** [CS2103-AY1819S1-F11-1/main#246]

**Comment by Hexinyiyi** [comment]
add n/Study For Finals s/2018-11-4 9pm e/2018-11-4 10pm rt/WEEKLY ru/2018-12-01
edit 1 s/2018-11-1 10am e/2018-11-1 11am rt/WEEKLY

**Comment by YezhongZ** [comment]
Fixed
