### ISSUE TITLE
As a lazy university student, I can interact with the scheduler using syntax closer to natural language

### ISSUE THREAD

**Issue by ChengYuuu** [CS2103-AY1819S1-F11-1/main#8]
so that I do not have to remember the command syntax.

**Comment by HEARTOFAL1ON** [comment]
Okay got it! `autocomplete` right?

**Comment by HEARTOFAL1ON** [comment]
Why is this priority low? Means not necessary to implement as feature? O_O

**Comment by HEARTOFAL1ON** [comment]
https://github.com/CS2103-AY1819S1-F11-1/main/pull/156
