### ISSUE TITLE
Create connection with Google Service and Google Calendar

### ISSUE THREAD

**Issue by YezhongZ** [CS2103-AY1819S1-F11-1/main#97]
Create connection with Google Calendar

**Comment by HEARTOFAL1ON** [comment]
I think you may need to make use of the Google API key. Do not be afraid to raise an issue on the issues forum if you are facing problems :)

**Comment by YezhongZ** [comment]
> I think you may need to make use of the Google API key. Do not be afraid to raise an issue on the issues forum if you are facing problems :)

Thx. I have already implemented that in the corresponding PR.
This issue is created for the issue-PR pair.
